// Generated by https://quicktype.io

import { Photo } from './photo';

export interface Member {
  id: number;
  userName: string;
  photoUrl: string;
  age: number;
  knownAs: string;
  createdAt: Date;
  lastActive: Date;
  gender: string;
  introduction: string;
  lookingFor: string;
  interest: string;
  city: string;
  country: string;
  photos: Photo[];
}
